package:
    name: flexdata
    version: "0.1.0"

source:
    path: ../

build:
    number: '0'

requirements:
    build:
        - python {{ python }}
        - tifffile
        - transforms3d

    run:
        - python
        - numpy
	- scipy
        - astra-toolbox
        - matplotlib
	- pyqtgraph
        - tqdm
        - imageio
        - tifffile
        - psutil
        - toml
        - transforms3d
        - paramiko

about:
    home: https://github.com/cicwi/flexdata
    license_file: LICENSE.md
    summary: "This project comprises IO routines that make life easier with Flex-Ray scanner."

extra:
    maintainers:
        - Alexander Kostenko
